### ISSUE TITLE
Create the homepage for the e-commerce-store

### ISSUE THREAD

**Issue by jamilu-jibrilla** [jamilu-jibrilla/e-commmerce-store#1]
**The homepage contains a product list and category section, the data to be displayed in both section should be pulled from an API. The API endpoint can be found in the API sections of this repository's read me file.**
 
- The product list section should look exactly like what is in the featured products section of the provided template.
- The category section should also look like the category section of the provided template.
- Check the repo's readme for link to download the template

**Comment by arcteggzz** [comment]
@jamilu-jibrilla I have completed this

**Comment by jamilu-jibrilla** [comment]
task completed ( component should be updated to have its data fetched from an endpoint)
